/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-11-20 00:33:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h3>index.html 과 index.jsp 차이</h3>\r\n");
      out.write("	<pre>\r\n");
      out.write("HTML : html, css, js 코드 작성 가능\r\n");
      out.write("	+ 정적 페이지 (미리 만들어둔 형태 그대로)		\r\n");
      out.write("	\r\n");
      out.write("jsp : html, css, js, java, el, jstl 작성 가능\r\n");
      out.write("	+ 동적 페이지(요청에 따라 응답화면 변함)	\r\n");
      out.write("	</pre>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<form action=\"el/test1.jsp\">\r\n");
      out.write("		문자열 입력 : <input type=\"text\" name=\"str\"> <br>\r\n");
      out.write("		정수 입력 : <input type=\"number\" name=\"intNum\"> <br>\r\n");
      out.write("		실수 입력 : <input type=\"text\" name=\"doubleNum\"> <br>\r\n");
      out.write("	\r\n");
      out.write("	<div>\r\n");
      out.write("		A <input type=\"checkbox\" name=\"check\" value=\"A\">\r\n");
      out.write("		B <input type=\"checkbox\" name=\"check\" value=\"B\">\r\n");
      out.write("		C <input type=\"checkbox\" name=\"check\" value=\"C\">\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		<button>제출하기</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<h1>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<a href=\"/el/scope\">Servlet/JSP 범위(scope)별 내장 객체 + EL 사용법</a>	\r\n");
      out.write("	</h1>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<h1>forward와 redirect</h1>\r\n");
      out.write("	\r\n");
      out.write("	<h3>forward : 요청 위임</h3>\r\n");
      out.write("	\r\n");
      out.write("	<pre>\r\n");
      out.write("		- 클라이언트 요청을 받은 Servlet/JSP가\r\n");
      out.write("		  직접 응답하는것이 아닌\r\n");
      out.write("		  다른 Servlet/JSP에\r\n");
      out.write("		  HttpServletRequest, HttpServletResponse\r\n");
      out.write("		  객체를 넘겨서(위임) 대신 응답하게 하는 것\r\n");
      out.write("		 \r\n");
      out.write("		- 요청 위임 시\r\n");
      out.write("		  RequestDispatcher(요청 발송자)를 이용\r\n");
      out.write("		 \r\n");
      out.write("		- 요청 위임할 JSP ***파일 경로*** 작성\r\n");
      out.write("		\r\n");
      out.write("		- 응답 화면(결과 페이지) 주소는\r\n");
      out.write("		  처음 Servlet이 요청 받은 주소 그대로!\r\n");
      out.write("	</pre>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"/fr/forward\">\r\n");
      out.write("		forward 입력 1 : <input type=\"text\" name=\"forwardInput1\">\r\n");
      out.write("		<br>\r\n");
      out.write("		forward 입력 2 : <input type=\"text\" name=\"forwardInput2\">\r\n");
      out.write("		<button>forward 확인하기</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	<h3>redirect (재요청, 다른 Servlet 요청)</h3>\r\n");
      out.write("	\r\n");
      out.write("	<pre>\r\n");
      out.write("		- 클라이언트의 요청을 받은 Servlet에서\r\n");
      out.write("		  직접 응답하지 않고,\r\n");
      out.write("		  다른 Servlet을 다시 요청하는 것\r\n");
      out.write("		 \r\n");
      out.write("		- 보통 Servlet 요청 처리 후\r\n");
      out.write("		  특정 JSP로 요청을 위임해\r\n");
      out.write("		  결과 화면을 응답해 주는 것이 아닌\r\n");
      out.write("		  (요청 받은 Servlet이 응답해줄 JSP가 없음)\r\n");
      out.write("		 \r\n");
      out.write("		  다른 Servlet을 다시 요청하여\r\n");
      out.write("		  다른 Servlet의 결과 화면을 응답해줌\r\n");
      out.write("		 \r\n");
      out.write("		 \r\n");
      out.write("	    - redirect는 다시 요청 하는 것!!!\r\n");
      out.write("	      -> 기존 req, resp 객체가 사라지고\r\n");
      out.write("	         새로운 req, resp 객체가 생성된다.\r\n");
      out.write("	        \r\n");
      out.write("	         -> request scope에 세팅된 값들이 모두 사라짐\r\n");
      out.write("	        \r\n");
      out.write("	    - redirect는 응답 화면의 주소가\r\n");
      out.write("	      처음 요청한 Servlet 주소가 아닌\r\n");
      out.write("	      재요청한 Servlet 주소로 변경된다\r\n");
      out.write("	     \r\n");
      out.write("	    - 다른 Servlet을 요청하기 위해서는\r\n");
      out.write("	      \"요청 주소\"를 작성해야 한다.\r\n");
      out.write("	</pre>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"/fr/redirect\">\r\n");
      out.write("		redirect 입력 1 : <input type=\"text\" name=\"redirectInput1\">\r\n");
      out.write("		<br>\r\n");
      out.write("		redirect 입력 2 : <input type=\"text\" name=\"redirectInput2\">\r\n");
      out.write("		<button>redirect 확인하기</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
